// Generated by CoffeeScript 1.4.0
(function() {

  if (!(location.hash.indexOf('state=glists-app-auth') < 0)) {
    window.location = chrome.extension.getURL('authenticate.html') + location.hash;
  }

}).call(this);
